import type { Metadata } from 'next';
import { Manrope, Great_Vibes } from 'next/font/google';
import { SpeedInsights } from '@vercel/speed-insights/next';
import '@/src/styles/globals.css';
import LenisWrapper from '@/src/components/lenis_wrapper/LenisWrapper';

const manrope = Manrope({
	subsets: ['latin', 'cyrillic'], // Поддержка кириллицы
	weight: ['300', '400', '500', '600', '700', '800'], // Выбираем нужные толщины
	display: 'swap', // Улучшает рендеринг
});

const great_vibes = Great_Vibes({
	subsets: ['latin', 'cyrillic'], // Поддержка кириллицы
	weight: ['400'], // Выбираем нужные толщины
	display: 'swap', // Улучшает рендеринг
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru' className={(manrope.className, great_vibes.className)}>
			<body>
				<LenisWrapper>{children}</LenisWrapper>

				<SpeedInsights />
			</body>
		</html>
	);
}
